export const errorMapTypes = {
  USER_ALREDY_EXISTS: 'User alredy Exist',
  USER_DONT_EXIST: 'User dont exist',
  INCORRECT_PASSWORD: 'Incorrect password',
  CLASSROOM_REQUEST_ERROR: 'Classroom request error',
  REQUEST_ERROR: 'RequestError, please tent again',
  MODULE_NOT_FOUD: 'Module dont exist',
  SUBMODULE_DONT_EXIST: 'SubModule not found',
  UPDATE_SUBMODULE_ERROR: 'Error in update submodule',
  ERROR_IN_DELETE_MODULE: 'Error in module delete',
  ERROR_IN_UPDATE_SUBMODULE: 'Error in update submodule',
  ERROR_IN_UPDATE_MODULE: 'Error in update module',
  ERROR_ADD_NEW_CLASSROOM: 'Add new classroom error',
  ERROR_ADD_NEW_CLASSROOM_DATA: 'Add new classroom data error',
  CLASSROOM_DONT_EXIST:'Classroom dont exist',
  TOKEN_NOT_FOUND: 'Token not found',
  ADM_NOT_DOUND: 'Adm not found',
  USER_COMMENT_NOT_FOUND: 'Comentário não acossiado a um usuário',
  CLASSROOM_COMMENT_NOT_FOUND: 'Comentário não acossiado a uma aula',
  COMMENT_NO_CONTENT: 'Comentário sem conteúdo',
  NO_UPDATE_COMMENT: 'Erro no servidor, Não foi possível atualizar o comentário',
  COMMENT_UPDATED_SUCCESS: 'Comentário atualizado com sucesso!',
}
