export const AuthTypes = {
  INIT_LOGIN: 'INIT_LOGIN',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGOUT: 'SIGOUT'
};

export const ModulesTypes = {
  INIT_REQUEST: 'INIT_REQUEST',
  REQUEST_SUCCESS: 'REQUEST_SUCCESS',
  REQUEST_FAIL: 'REQUEST_FAIL',
  ADD_NEW_MODULE: 'ADD_NEW_MODULE',
  EDIT_MODULE_MODULE: 'EDIT_MODULE_MODULE',
  DELETE_MODULE: 'DELETE_MODULE',
  SELECT_MODULE: 'SELECT_MODULE',
};
